services:
  - type: web
    name: proyecto-codex
    env: python
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "0"
      - key: LOG_LEVEL
        value: INFO
      - key: FLASK_APP
        value: app:create_app
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    preDeployCommand: |
      alembic -c migrations/alembic.ini upgrade head && \
      FLASK_APP=app:create_app flask seed-admin --email admin@admin.com --password admin123
    startCommand: gunicorn -w 3 wsgi:app
    healthCheckPath: /healthz
