services:
  - type: web
    name: proyecto-codex
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: >
      alembic -c migrations/alembic.ini upgrade head &&
      FLASK_APP=app:create_app flask seed-admin --email admin@admin.com --password admin123
    startCommand: gunicorn -w 3 wsgi:app
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codex-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://localhost:3000
