services:
  - type: web
    name: proyecto-codex
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: |
      set -euxo pipefail
      python - <<'PY'
      import os
      from sqlalchemy import create_engine, text

      engine = create_engine(os.environ["DATABASE_URL"])
      with engine.begin() as conn:
          conn.execute(
              text(
                  "ALTER TABLE IF EXISTS alembic_version "
                  "ALTER COLUMN version_num TYPE VARCHAR(128)"
              )
          )
      print("OK: alembic_version.version_num ensure 128")
      PY
      python -m alembic -c migrations/alembic.ini upgrade head
      python -m flask --app app:create_app seed-admin --email admin@admin.com --password admin123
    startCommand: gunicorn -w 2 -k gthread -t 120 -b 0.0.0.0:$PORT 'app:create_app()'
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codex-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: SECURITY_PASSWORD_SALT
        generateValue: true
