services:
  - type: web
    name: proyecto-codex
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python -c "import os,psycopg; conn=psycopg.connect(os.environ['DATABASE_URL']); cur=conn.cursor(); cur.execute('ALTER TABLE IF EXISTS alembic_version ALTER COLUMN version_num TYPE VARCHAR(64);'); conn.commit(); cur.close(); conn.close()" && alembic -c migrations/alembic.ini upgrade head && FLASK_APP=app:create_app flask seed-admin --email admin@admin.com --password admin123
    startCommand: gunicorn -w 3 wsgi:app
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: codex-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
