name: CI - Coverage
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  coverage-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: [api, auth, models, routes, services, utils]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov

      - name: Run pytest for ${{ matrix.part }} (coverage + junit)
        # 👇 importante: opcion correcta con "="
        run: |
          set -euxo pipefail
          TARGET="app/${{ matrix.part }}"
          if [ -d "$TARGET" ]; then
            pytest -q --maxfail=1 --disable-warnings \
              --cov="$TARGET" --cov-branch \
              --cov-report=xml:coverage-${{ matrix.part }}.xml \
              --junitxml=junit-${{ matrix.part }}.xml -o junit_family=legacy
          else
            pytest -q --maxfail=1 --disable-warnings \
              --cov=app --cov-branch \
              --cov-report=xml:coverage-${{ matrix.part }}.xml \
              --junitxml=junit-${{ matrix.part }}.xml -o junit_family=legacy
          fi

      - name: Upload test results (Test Analytics) - ${{ matrix.part }}
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: junit-${{ matrix.part }}.xml
          flags: ${{ matrix.part }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      # (Coverage uploads centralizados en ci-coverage-stable.yml)

  coverage-all:
    runs-on: ubuntu-latest
    needs: coverage-matrix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov

      - name: Run full suite (coverage + junit)
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=app --cov-branch \
            --cov-report=xml:coverage.xml \
            --junitxml=junit.xml -o junit_family=legacy

      - name: Upload test results (Test Analytics) - all
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: junit.xml
          flags: all
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      # (Coverage uploads centralizados en ci-coverage-stable.yml)
