name: CI (stable coverage)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov coverage
      - name: Run tests (with coverage)
        run: |
          pytest
          test -f coverage.xml || { echo "coverage.xml missing"; exit 1; }
      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          use_oidc: true
          verbose: true
          fail_ci_if_error: true
