name: CI - Coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coverage-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: [api, auth, models, routes, services, utils]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov

      - name: Run pytest for ${{ matrix.part }}
        run: |
          TARGET="app/${{ matrix.part }}"
          # Si el folder no existe, hacemos un run mínimo para no fallar
          if [ -d "$TARGET" ]; then
            pytest -q --maxfail=1 --disable-warnings \
              --cov="$TARGET" --cov-branch \
              --cov-report=xml:coverage-${{ matrix.part }}.xml
          else
            echo "Folder $TARGET no existe; ejecutando tests básicos"
            pytest -q --maxfail=1 --disable-warnings \
              --cov=app --cov-branch \
              --cov-report=xml:coverage-${{ matrix.part }}.xml
          fi

      - name: Upload to Codecov (${{ matrix.part }})
        uses: codecov/codecov-action@v5
        with:
          files: coverage-${{ matrix.part }}.xml
          flags: ${{ matrix.part }}
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  # Job extra (opcional) para ejecutar toda la suite una vez
  coverage-all:
    runs-on: ubuntu-latest
    needs: coverage-matrix
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest pytest-cov
      - name: Run full suite
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=app --cov-branch --cov-report=xml:coverage.xml \
            --cov-report=term-missing
      - name: Upload combined
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
