name: CI - Coverage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FLASK_APP: app:create_app
      FLASK_CONFIG: testing
      DATABASE_URL: sqlite:///./.tmp/test.db
      SQLALCHEMY_DATABASE_URI: sqlite:///./.tmp/test.db
      PYTHONWARNINGS: ignore::DeprecationWarning

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # asegúrate de tener pytest-cov (si no está en requirements)
          pip install pytest-cov

      - name: Prepare temp dirs
        run: mkdir -p .tmp

      - name: Upgrade DB (migrations)
        run: |
          python manage.py db upgrade || true
        env:
          FLASK_APP: app:create_app
          FLASK_CONFIG: testing

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings --cov=app --cov-report=xml

      # Si estás usando Codecov, descomenta estas 4 líneas y guarda el token en secrets
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     fail_ci_if_error: false
