name: CI (stable coverage)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term

      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          use_oidc: true
          token: ${{ secrets.CODECOV_TOKEN }}   # <- quítalo cuando instales la App
          verbose: true
          fail_ci_if_error: true
