name: CI (PR)

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install & test (PR-safe)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest
          pytest -q --disable-warnings --maxfail=1
