name: CI (basic)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_ENV: testing
      SECRET_KEY: dummy-for-ci
      DATABASE_URL: sqlite:///test.db
      AUTH_DISABLED: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings
